# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: "https://huangzhw.github.io"
date_format: "ordinal"
title: Everyday
subtitle: "Everyday"
description: "Everday的个人博客"
keywords: Everyday
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: HuangZhw
organization: 
organization_url:
github_username: huangzhw
location: HangZhou, China
email: huang_zhw@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: huangzhw/huangzhw.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: huangzhw
    repo: blog-comments
    oauth:
        client_id: 5454ac02575c4228492d
        client_secret: 49c237bc4fedc06bcda1d63f3ec8a4a4d2f0ab7f
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: huangzhw
    repo: blog-comments
    clientID: 5454ac02575c4228492d
    clientSecret: 49c237bc4fedc06bcda1d63f3ec8a4a4d2f0ab7f
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
